#![allow(clippy::excessive_precision)]
// Generated by tools/generate-halfband.py. SHA-256 of little-endian f32 bytes:
// 009bdbf7e7f722338fd9cb993c86f230c062d4b8d918905e14792bbd2805a4cb
pub(crate) const HALF_BAND_TAPS: [f32; 129] = [
    0.000000000e+00,
    -8.009405065e-06,
    0.000000000e+00,
    1.866828279e-05,
    0.000000000e+00,
    -3.601562275e-05,
    0.000000000e+00,
    6.253029278e-05,
    0.000000000e+00,
    -1.012305074e-04,
    0.000000000e+00,
    1.557236974e-04,
    0.000000000e+00,
    -2.302530775e-04,
    0.000000000e+00,
    3.297412477e-04,
    0.000000000e+00,
    -4.598326923e-04,
    0.000000000e+00,
    6.269378937e-04,
    0.000000000e+00,
    -8.382845554e-04,
    0.000000000e+00,
    1.101983595e-03,
    0.000000000e+00,
    -1.427121111e-03,
    0.000000000e+00,
    1.823893865e-03,
    0.000000000e+00,
    -2.303811954e-03,
    0.000000000e+00,
    2.880004467e-03,
    0.000000000e+00,
    -3.567681881e-03,
    0.000000000e+00,
    4.384836648e-03,
    0.000000000e+00,
    -5.353307351e-03,
    0.000000000e+00,
    6.500419229e-03,
    0.000000000e+00,
    -7.861539721e-03,
    0.000000000e+00,
    9.484170936e-03,
    0.000000000e+00,
    -1.143468916e-02,
    0.000000000e+00,
    1.380990911e-02,
    0.000000000e+00,
    -1.675796323e-02,
    0.000000000e+00,
    2.051847987e-02,
    0.000000000e+00,
    -2.550663054e-02,
    0.000000000e+00,
    3.250920400e-02,
    0.000000000e+00,
    -4.321676120e-02,
    0.000000000e+00,
    6.203276291e-02,
    0.000000000e+00,
    -1.051188186e-01,
    0.000000000e+00,
    3.179816604e-01,
    5.000020266e-01,
    3.179816604e-01,
    0.000000000e+00,
    -1.051188186e-01,
    0.000000000e+00,
    6.203276291e-02,
    0.000000000e+00,
    -4.321676120e-02,
    0.000000000e+00,
    3.250920400e-02,
    0.000000000e+00,
    -2.550663054e-02,
    0.000000000e+00,
    2.051847987e-02,
    0.000000000e+00,
    -1.675796323e-02,
    0.000000000e+00,
    1.380990911e-02,
    0.000000000e+00,
    -1.143468916e-02,
    0.000000000e+00,
    9.484170936e-03,
    0.000000000e+00,
    -7.861539721e-03,
    0.000000000e+00,
    6.500419229e-03,
    0.000000000e+00,
    -5.353307351e-03,
    0.000000000e+00,
    4.384836648e-03,
    0.000000000e+00,
    -3.567681881e-03,
    0.000000000e+00,
    2.880004467e-03,
    0.000000000e+00,
    -2.303811954e-03,
    0.000000000e+00,
    1.823893865e-03,
    0.000000000e+00,
    -1.427121111e-03,
    0.000000000e+00,
    1.101983595e-03,
    0.000000000e+00,
    -8.382845554e-04,
    0.000000000e+00,
    6.269378937e-04,
    0.000000000e+00,
    -4.598326923e-04,
    0.000000000e+00,
    3.297412477e-04,
    0.000000000e+00,
    -2.302530775e-04,
    0.000000000e+00,
    1.557236974e-04,
    0.000000000e+00,
    -1.012305074e-04,
    0.000000000e+00,
    6.253029278e-05,
    0.000000000e+00,
    -3.601562275e-05,
    0.000000000e+00,
    1.866828279e-05,
    0.000000000e+00,
    -8.009405065e-06,
    0.000000000e+00,
];

pub(crate) struct HalfBandDecimator {
    history: [f32; 129],
    write: usize,
    index: u64,
}
impl HalfBandDecimator {
    fn new() -> Self {
        Self {
            history: [0.0; 129],
            write: 0,
            index: 0,
        }
    }
    fn push(&mut self, sample: f32) -> Option<f32> {
        self.history[self.write] = sample;
        let emit = self.index & 1 == 0;
        self.index = self.index.wrapping_add(1);
        if !emit {
            self.write = (self.write + 1) % 129;
            return None;
        }
        let mut out = 0.0;
        let mut pos = self.write;
        for tap in HALF_BAND_TAPS {
            if tap != 0.0 {
                out += tap * self.history[pos];
            }
            pos = if pos == 0 { 128 } else { pos - 1 };
        }
        self.write = (self.write + 1) % 129;
        Some(out)
    }
}
pub(crate) struct Decimator4 {
    first: HalfBandDecimator,
    second: HalfBandDecimator,
}
impl Decimator4 {
    pub(crate) fn new() -> Self {
        Self {
            first: HalfBandDecimator::new(),
            second: HalfBandDecimator::new(),
        }
    }
    pub(crate) fn process(&mut self, input: [f32; 4]) -> f32 {
        let mut result = None;
        for sample in input {
            if let Some(x) = self.first.push(sample) {
                if let Some(y) = self.second.push(x) {
                    result = Some(y);
                }
            }
        }
        result.expect("four 4x samples always yield one base sample")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[allow(clippy::needless_range_loop)]
    fn sha256(bytes: &[u8]) -> [u8; 32] {
        const K: [u32; 64] = [
            0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4,
            0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe,
            0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f,
            0x4a7484aa, 0x5cb0a9dc, 0x76f988da, 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
            0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc,
            0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
            0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116,
            0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
            0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7,
            0xc67178f2,
        ];
        let mut data = bytes.to_vec();
        let bit_len = (data.len() as u64) * 8;
        data.push(0x80);
        while data.len() % 64 != 56 {
            data.push(0);
        }
        data.extend_from_slice(&bit_len.to_be_bytes());
        let mut h = [
            0x6a09e667u32,
            0xbb67ae85,
            0x3c6ef372,
            0xa54ff53a,
            0x510e527f,
            0x9b05688c,
            0x1f83d9ab,
            0x5be0cd19,
        ];
        for block in data.chunks_exact(64) {
            let mut w = [0u32; 64];
            for i in 0..16 {
                w[i] = u32::from_be_bytes(block[i * 4..i * 4 + 4].try_into().unwrap());
            }
            for i in 16..64 {
                let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
                let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
                w[i] = w[i - 16]
                    .wrapping_add(s0)
                    .wrapping_add(w[i - 7])
                    .wrapping_add(s1);
            }
            let [mut a, mut b, mut c, mut d, mut e, mut f, mut g, mut hh] = h;
            for i in 0..64 {
                let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
                let ch = (e & f) ^ (!e & g);
                let t1 = hh
                    .wrapping_add(s1)
                    .wrapping_add(ch)
                    .wrapping_add(K[i])
                    .wrapping_add(w[i]);
                let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
                let maj = (a & b) ^ (a & c) ^ (b & c);
                let t2 = s0.wrapping_add(maj);
                hh = g;
                g = f;
                f = e;
                e = d.wrapping_add(t1);
                d = c;
                c = b;
                b = a;
                a = t1.wrapping_add(t2);
            }
            for (state, value) in h.iter_mut().zip([a, b, c, d, e, f, g, hh]) {
                *state = state.wrapping_add(value);
            }
        }
        let mut out = [0u8; 32];
        for (i, value) in h.into_iter().enumerate() {
            out[i * 4..i * 4 + 4].copy_from_slice(&value.to_be_bytes());
        }
        out
    }

    #[test]
    fn coefficients_are_normative_and_symmetric() {
        assert_eq!(HALF_BAND_TAPS.len(), 129);
        assert!((HALF_BAND_TAPS[64] - 0.5000020266).abs() < 1e-7);
        for i in 0..129 {
            assert_eq!(HALF_BAND_TAPS[i], HALF_BAND_TAPS[128 - i]);
            if i != 64 && (i as isize - 64) % 2 == 0 {
                assert_eq!(HALF_BAND_TAPS[i], 0.0);
            }
        }
        let bytes: Vec<_> = HALF_BAND_TAPS
            .iter()
            .flat_map(|tap| tap.to_le_bytes())
            .collect();
        let digest = sha256(&bytes).map(|byte| format!("{byte:02x}")).concat();
        assert_eq!(
            digest,
            "009bdbf7e7f722338fd9cb993c86f230c062d4b8d918905e14792bbd2805a4cb"
        );
    }
    #[test]
    fn response_meets_normative_edges() {
        let magnitude_db = |frequency: f64| {
            let (real, imaginary) = HALF_BAND_TAPS.iter().enumerate().fold(
                (0.0, 0.0),
                |(real, imaginary), (index, tap)| {
                    let angle = -std::f64::consts::TAU * frequency * index as f64;
                    (
                        real + f64::from(*tap) * angle.cos(),
                        imaginary + f64::from(*tap) * angle.sin(),
                    )
                },
            );
            20.0 * real.hypot(imaginary).max(1e-300).log10()
        };
        let passband: Vec<_> = (0..=2_200)
            .map(|index| magnitude_db(0.22 * index as f64 / 2_200.0))
            .collect();
        let passband_ripple = passband.iter().copied().fold(f64::NEG_INFINITY, f64::max)
            - passband.iter().copied().fold(f64::INFINITY, f64::min);
        let stopband_peak = (0..=2_200)
            .map(|index| magnitude_db(0.28 + 0.22 * index as f64 / 2_200.0))
            .fold(f64::NEG_INFINITY, f64::max);
        assert!(
            passband_ripple <= 0.001,
            "passband ripple {passband_ripple} dB"
        );
        assert!(stopband_peak <= -90.0, "stopband peak {stopband_peak} dB");
    }

    #[test]
    fn cascade_latency_is_48_base_frames() {
        let mut d = Decimator4::new();
        let mut peak = (0, 0.0f32);
        for n in 0..100 {
            let y = d.process(if n == 0 {
                [1.0, 0.0, 0.0, 0.0]
            } else {
                [0.0; 4]
            });
            if y.abs() > peak.1.abs() {
                peak = (n, y);
            }
        }
        assert_eq!(peak.0, 48);
    }
}
