/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AudioEngine {
  constructor()
  start(): void
  stop(): void
  setGate(enabled: boolean): void
  applyPatch(serializedPatch: string): void
  takeRuntimeError(): boolean
}
