/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AudioEngine {
  constructor()
  start(): void
  stop(): void
  tryApplyPatch(serializedPatch: string): boolean
  tryApplyPatchAndNoteOn(serializedPatch: string): boolean
  tryNoteOff(): boolean
  takeRuntimeError(): boolean
}
